;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                        ;
;                              OCamlFormat                               ;
;                                                                        ;
;            Copyright (c) Facebook, Inc. and its affiliates.            ;
;                                                                        ;
;      This source code is licensed under the MIT license found in       ;
;      the LICENSE file in the root directory of this source tree.       ;
;                                                                        ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(ocamllex Mll_lexer)

(menhir
 (infer false)
 (flags --table)
 (modules Mll_parser))

(library
 (name ocamlformat_mll)
 (public_name ocamlformat-lib.mll)
 (flags
  (:standard -open Ocamlformat_ocaml_common))
 (libraries menhirLib ocamlformat_ocaml_common))
